const API_URL='https://script.google.com/macros/s/AKfycbxvqJpcrAHSgxTDJ7-U_spCaCmJf2oCbOl5qo3ULdH0lWdggkJYqJhkQCLzkib0t_yEvg/exec';
let sessao={token:localStorage.getItem('vf_token'),usuario:JSON.parse(localStorage.getItem('vf_usuario')||'null')};
document.addEventListener('DOMContentLoaded',iniciarApp);
function iniciarApp(){configurarLogin();configurarLogout();configurarModulos();if(sessao.token&&sessao.usuario)abrirHome();else abrirLogin()}
function configurarLogin(){document.getElementById('form-login').addEventListener('submit',async e=>{e.preventDefault();const usuario=document.getElementById('usuario').value.trim();const senha=document.getElementById('senha').value;const botao=document.getElementById('btn-login');const mensagem=document.getElementById('mensagem-login');mensagem.textContent='';botao.disabled=true;botao.textContent='Entrando...';try{const resposta=await chamarApi({action:'login',usuario,senha});if(!resposta.sucesso)throw new Error(resposta.erro||'Não foi possível entrar.');sessao.token=resposta.token;sessao.usuario=resposta.usuario;localStorage.setItem('vf_token',resposta.token);localStorage.setItem('vf_usuario',JSON.stringify(resposta.usuario));abrirHome()}catch(err){mensagem.textContent=err.message}finally{botao.disabled=false;botao.textContent='Entrar'}})}
function abrirHome(){document.getElementById('tela-login').classList.add('escondido');document.getElementById('tela-home').classList.remove('escondido');document.getElementById('nome-usuario').textContent=(sessao.usuario?.nome||'')+' 👋'}
function abrirLogin(){document.getElementById('tela-home').classList.add('escondido');document.getElementById('tela-login').classList.remove('escondido')}
function configurarLogout(){document.getElementById('btn-logout').addEventListener('click',sair)}
async function sair(){try{if(sessao.token)await chamarApi({action:'logout',token:sessao.token})}catch(err){console.warn(err)}localStorage.removeItem('vf_token');localStorage.removeItem('vf_usuario');sessao={token:null,usuario:null};abrirLogin()}
function configurarModulos(){document.querySelectorAll('.modulo').forEach(b=>b.addEventListener('click',()=>abrirModulo(b.dataset.modulo)))}
function abrirModulo(modulo){const nomes={financeiro:'🪙 Financeiro',mercado:'🛒 Mercado',relatorios:'📊 Relatórios',calendario:'📅 Calendário',comprovantes:'🧾 Comprovantes',configuracoes:'⚙️ Configurações'};alert(nomes[modulo]||modulo)}
async function chamarApi(dados){if(API_URL.includes('COLE_AQUI'))throw new Error('Configure a URL da API no arquivo app.js.');const r=await fetch(API_URL,{method:'POST',headers:{'Content-Type':'text/plain;charset=utf-8'},body:JSON.stringify(dados)});if(!r.ok)throw new Error('Erro de comunicação com o servidor.');const t=await r.text();try{return JSON.parse(t)}catch(err){console.error(t);throw new Error('Resposta inválida da API.')}}
